source ~/.vim/configs/_general.vim
source ~/.vim/configs/coc.nvim.vim
source ~/.vim/configs/fzf.vim
source ~/.vim/configs/gitlink-vim.vim
source ~/.vim/configs/nerdcommenter.vim
source ~/.vim/configs/nerdtree.vim
source ~/.vim/configs/statusline.vim
source ~/.vim/configs/vim-fugitive.vim
source ~/.vim/configs/vim-go.vim
