source ~/.vim/configs/_general.vim
source ~/.vim/configs/coc.nvim.vim
source ~/.vim/configs/darcula.theme.vim
source ~/.vim/configs/fzf.vim
source ~/.vim/configs/nerdcommenter.vim
source ~/.vim/configs/nerdtree.vim
source ~/.vim/configs/typescript-vim.vim
source ~/.vim/configs/vim-autoformat.vim
source ~/.vim/configs/vim-fugitive.vim
source ~/.vim/configs/vimspector.vim
